### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by martin0409** [seraph98/RollerCoin_Assistant_Tool#1]
Hi 
What is your python version ?

I try run Your script , but without any success

> 
Statistics:
 Time running: 0:00:02.360800
 Played Games:  1

Traceback (most recent call last):
  File "bot.py", line 65, in <module>
    main()
  File "bot.py", line 51, in main
    if bot().can_start():
  File "C:\Users\ScarFace1983\Downloads\RollerCoin_Assistant_Tool-master_2\RollerCoin_Assistant_Tool-master\rc_bots\BotCoinFlipBot.py", line 42, in can_start
    return check_image(self.head_img_path)
  File "C:\Users\ScarFace1983\Downloads\RollerCoin_Assistant_Tool-master_2\RollerCoin_Assistant_Tool-master\rc_util\game_util.py", line 90, in check_image
    b, _ = find_image(img, screen_grab())
  File "C:\Users\ScarFace1983\Downloads\RollerCoin_Assistant_Tool-master_2\RollerCoin_Assistant_Tool-master\rc_util\game_util.py", line 81, in find_image
    searchBox=search_box)
TypeError: matchTemplates() got an unexpected keyword argument 'N_object'
> 

Thanks!

**Comment by Azarkooo** [comment]
yes same problem

**Comment by Azarkooo** [comment]
'NoneType' object has no attribute 'dtype' problem
